{{- if .Values.worker.applicationLogging.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bdba.fullname" . }}-worker-fluentbit-config
  labels:
{{ include "bdba.labels" . | indent 4 }}
data:
  fluent-bit.conf: |
    [SERVICE]
        Daemon       Off
        Flush        5
        Log_Level    info
        HTTP_Server  Off
        Parsers_File /bdba-fluentbit/parsers.conf

    [INPUT]
        Name         tail
        Tag          worker
        Path         /app-log/celery.log
        Parser       json
        DB           /app-log/celery.db

    [FILTER]
        Name record_modifier
        Match *
        Record hostname ${HOSTNAME}

    [OUTPUT]
        Name         forward
        Match        *
        Host         {{ template "bdba.fluentd.fullname" . }}

  parsers.conf: |
    [PARSER]
        Name        json
        Format      json
        Time_Key    timestamp
        Time_Format %Y-%m-%dT%H:%M:%S.%L

---
{{- end }}
apiVersion: apps/v1
{{- if .Values.worker.storageClass }}
kind: StatefulSet
{{- else }}
kind: Deployment
{{- end }}
metadata:
  name: {{ include "bdba.fullname" . }}-worker
  labels:
{{ include "bdba.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.worker.replicas }}
  {{- if .Values.worker.storageClass }}
  serviceName: {{ include "bdba.fullname" . }}-worker-svc
  updateStrategy:
    type: RollingUpdate
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bdba.name" . }}-worker
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      name: {{ include "bdba.name" . }}-worker
      labels:
        app.kubernetes.io/name: {{ include "bdba.name" . }}-worker
        app.kubernetes.io/instance: {{ .Release.Name }}
        release: {{ .Release.Name | quote }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-user.yaml") . | sha256sum }}
        checksum/services: {{ include (print $.Template.BasePath "/configmap-services.yaml") . | sha256sum }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}-worker
          image: "{{ .Values.worker.repository }}:{{ .Values.worker.tag }}"
          imagePullPolicy: {{ .Values.worker.pullPolicy }}
          readinessProbe:
            exec:
              command: ["/docker-healthcheck.sh" ]
            initialDelaySeconds: 15
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 35
          livenessProbe:
            exec:
              command: ["/docker-healthcheck.sh" ]
            initialDelaySeconds: 15
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 35
          resources:
            requests:
              cpu: {{ mul .Values.worker.concurrency 250 }}m
              memory: {{ mul .Values.worker.concurrency .Values.worker.memoryPerScanner }}Gi
              {{- if not .Values.worker.storageClass }}
              ephemeral-storage: {{ mul .Values.worker.concurrency .Values.worker.storagePerScanner}}Gi
              {{- end }}
            limits:
              cpu: {{ mul .Values.worker.concurrency 2 }}
              memory: {{ mul .Values.worker.concurrency 6}}Gi
              {{- if not .Values.worker.storageClass }}
              ephemeral-storage: {{ mul .Values.worker.concurrency 100}}Gi
              {{- end }}
          env:
            - name: SKIP_FRONTEND_ANNOUNCE
              value: "no"
            - name: SCANNER_CONCURRENCY
              value: {{ .Values.worker.concurrency | quote }}
            - name: BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: bdba-rabbitmq-broker-url
                  key: host
            - name: BROKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "bdba.rabbitmq.passwordSecretName" . }}
                  key: rabbitmq-password
            {{- if .Values.httpProxy }}
            - name: HTTP_PROXY
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bdba.fullname" . }}-user-configmap
                  key: HTTP_PROXY
            - name: http_proxy
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bdba.fullname" . }}-user-configmap
                  key: HTTP_PROXY
            - name: HTTPS_PROXY
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bdba.fullname" . }}-user-configmap
                  key: HTTP_PROXY
            - name: https_proxy
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bdba.fullname" . }}-user-configmap
                  key: HTTP_PROXY
            {{- end }}
            {{- if .Values.httpNoProxy }}
            - name: NO_PROXY
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bdba.fullname" . }}-user-configmap
                  key: NO_PROXY
            - name: no_proxy
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bdba.fullname" . }}-user-configmap
                  key: NO_PROXY
            {{- end }}
            {{- if .Values.worker.applicationLogging }}
            - name: TASKS_LOG_FILE
              value: /app-log/celery.log
            {{- end }}
            {{- include "bdba.s3env" . | nindent 12 }}
          volumeMounts:
            - name: {{ include "bdba.fullname" . }}-worker-applog
              mountPath: /app-log
            {{- if .Values.worker.storageClass }}
            - name: {{ include "bdba.name" . }}-worker-pvc
              mountPath: /tmp
            {{- else }}
            - name: {{ include "bdba.fullname" . }}-worker-tmp
              mountPath: /tmp
            {{- end }}
            - name: {{ include "bdba.fullname" . }}-worker-var-tmp
              mountPath: /var/tmp
            {{- if .Values.rootCASecret }}
            - name: ca-store
              mountPath: /usr/local/share/ca-certificates/appcheck/
              readOnly: true
            {{- end }}
          securityContext:
            readOnlyRootFilesystem: true
        {{- if .Values.worker.applicationLogging.enabled }}
        - name: {{ .Chart.Name }}-worker-fluentbit
          image: "{{ .Values.fluentbit.repository }}:{{ .Values.fluentbit.tag }}"
          imagePullPolicy: {{ .Values.fluentbit.pullPolicy }}
          command: ["/fluent-bit/bin/fluent-bit", "-c", "/bdba-fluentbit/fluent-bit.conf"]
          volumeMounts:
            - name: {{ include "bdba.fullname" . }}-worker-applog
              mountPath: /app-log
            - name: {{ include "bdba.fullname" . }}-worker-fluentbit-config
              mountPath: /bdba-fluentbit/
        {{- end }}
      # Termination graceperiod needs to be long for worker to be able to finish
      terminationGracePeriodSeconds: {{ .Values.worker.terminationGracePeriodSeconds }}
      {{- if .Values.worker.securityContext.enabled }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
      {{- end }}
      volumes:
      - name: {{ include "bdba.fullname" . }}-worker-applog
        emptyDir: {}
      {{- if not .Values.worker.storageClass }}
      - name: {{ include "bdba.fullname" . }}-worker-tmp
        emptyDir: {}
      {{- end }}
      - name: {{ include "bdba.fullname" . }}-worker-var-tmp
        emptyDir: {}
      {{- if .Values.rootCASecret }}
      - name: ca-store
        secret:
          secretName: {{ .Values.rootCASecret }}
      {{- end }}
      {{- if .Values.worker.applicationLogging.enabled }}
      - name: {{ include "bdba.fullname" . }}-worker-fluentbit-config
        configMap:
          name: {{ include "bdba.fullname" . }}-worker-fluentbit-config
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: {{ include "bdba.name" . }}-worker
              topologyKey: "kubernetes.io/hostname"
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: rabbitmq
              topologyKey: "kubernetes.io/hostname"
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: postgresql
              topologyKey: "kubernetes.io/hostname"
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: minio
              topologyKey: "kubernetes.io/hostname"
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  {{- if .Values.worker.storageClass }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "bdba.name" . }}-worker-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.worker.storageClass }}
        resources:
          requests:
            storage: {{ mul .Values.worker.concurrency .Values.worker.storagePerScanner}}Gi
  {{- end }}
